openapi: 3.1.0
info:
  title: User API
  version: 1.0.0
  description: Basic user API
paths:
  /users/v1:
    get:
      tags:
       - Users
      summary: Get all users
      responses:
        '200':
          description: 'List of users'
